/**
 * Alexandria
 * Alexandria
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleModuleInfo } from './moduleModuleInfo';


export interface Module { 
    path?: string;
    name?: string;
    has_readme?: boolean;
    module_info?: ModuleModuleInfo;
}

