/**
 * Alexandria
 * Alexandria
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProviderDetailsSigningKeys } from './providerDetailsSigningKeys';


export interface ProviderDetails { 
    protocols?: Array<string>;
    os?: string;
    arch?: string;
    filename?: string;
    download_url?: string;
    shasums_url?: string;
    shasums_signature_url?: string;
    shasum?: string;
    signing_keys?: ProviderDetailsSigningKeys;
}

