/**
 * Alexandria
 * Alexandria
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProviderVersionVersionsInnerPlatformsInner } from './providerVersionVersionsInnerPlatformsInner';


export interface ProviderVersionVersionsInner { 
    version?: string;
    protocols?: Array<string>;
    platforms?: Array<ProviderVersionVersionsInnerPlatformsInner>;
}

